### PR TITLE
Info links

### PR DESCRIPTION
**Pull request by dliptai**
Add clickable info link for each data field on web interface

### CODE REVIEW

**Comment by 2sn** [comment]
@dliptai I see there is file templates, but this is not yet ready to merge otherwise?

**Comment by dliptai** [comment]
@2sn Can be merged if you want. But it would be better to actually include some useful info, instead of just having empty files.
I was going to leave that up to you and/or @conradtchan

**Comment by 2sn** [comment]
@dliptai I did a test deploy to `starfit.xyz` but I think the deplot scripts (for server or full playbook) do not create the info directory and stuff in it:
```shell
[root@starfit html]# echo $HOSTNAME
starfit.xyz
[root@starfit html]# pwd
/var/www/html
[root@starfit html]# ls -latr
total 76
drwxr-xr-x. 4 root root   4096 Jun 17 11:13 ..
lrwxrwxrwx. 1 root apache    9 Oct 14 07:34 data -> /srv/data
-rw-r--r--. 1 root apache 1928 Oct 18 12:52 README.txt
-rw-r--r--. 1 root apache   20 Oct 18 12:52 config.yml
-rwxr-xr-x. 1 root apache 1766 Oct 18 12:52 run
-rw-r--r--. 1 root apache   40 Oct 18 12:52 robots.txt
-rw-r--r--. 1 root apache 6003 Oct 18 12:52 job.py
-rwxr-xr-x. 1 root apache 1115 Oct 18 12:52 index.html
-rw-r--r--. 1 root apache 1685 Oct 18 12:52 index.css
drwxr-xr-x. 2 root apache 4096 Oct 18 12:52 images
-rwxr-xr-x. 1 root apache  266 Oct 18 12:52 unsubscribe
drwxr-xr-x. 2 root apache 4096 Oct 20 01:40 __pycache__
-rw-r--r--. 1 root apache 1107 Oct 22 23:19 scripts.js
-rw-r--r--. 1 root apache  142 Oct 22 23:19 header.py
-rw-r--r--. 1 root apache 6274 Oct 22 23:19 utils.py
drwxr-xr-x. 2 root apache 4096 Oct 22 23:19 templates
-rw-r--r--. 1 root apache  882 Oct 22 23:32 deploy_info
drwxr-xr-x. 5 root apache 4096 Oct 22 23:32 .
```

**Comment by 2sn** [comment]
Note that I changed the link for DB info to point to a file on the server, `databases`  in the same directory where they live.

**Comment by 2sn** [comment]
@dliptai OK, I try deploy from this branch to `starfit.xyz`.

**Comment by 2sn** [comment]
@dliptai OK, seems to work.  Thanks a lot!  I assume we can merge into main branch?

**Pull request merged**
